export const DEFAULT_IMAGE = "/subtle-starfield.mp4";

export const EFFECT_DEFAULTS = {
  maxParticles: 262144,
  density: 4,
  size: 3.8,
  pearlTint: 1.25,
  separation: 72,
  cursorArea: 0.24,
  effectStyle: "energy",
  imageWarp: true,
  imageFade: true,
  revealHold: 0.4,
  revealDepth: 2,
  smoke: 0.16,
  smoothness: 8,
  arcGlow: true,
  pearlMaskReveal: false,
  pulseScale: 1.8,
  glowScale: 1.0,
  glowOpacity: 1.0,
  glowColor: "#8eefff",
  filterOverlay: false,
  globalComposite: false,
  globalCompositeLayers: {
    frost: true,
    rgb: true,
    bloom: true,
    streaks: true,
    corners: true,
    grain: true,
    fluid: true,
  },
};
